image: php:7.4-fpm

pipelines:
  default:
    - step:
        name: Building App & Testing App
        script:
          - apt-get update && apt-get install -qy vim cron git curl libpng-dev libonig-dev libxml2-dev libzip-dev zip unzip
          - docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip
          - ln -f -s .env.pipelines .env
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - php artisan migrate:fresh --seed
          - php artisan passport:install
          - php artisan serve &
          - sleep 5
          - php artisan test
          - curl -vk http://localhost:8000
        services:
          - mysql

    - step:
        name: Composer install
        image: php:7.4
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --prefer-dist --optimize-autoloader --no-dev
        artifacts:
          - vendor/**
          - bootstrap/cache/*.php

#    - step:
#        name: Deploying on Production
#        deployment: production
#        script:
#          - pipe: atlassian/google-app-engine-deploy:0.7.3
#            variables:
#              KEY_FILE: $KEY_FILE
#              PROJECT: $PROJECT
#              APP_STORAGE: "/tmp"
#              VIEW_COMPILED_PATH: "/tmp"

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: "laravel"
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: "laravel"
        MYSQL_PASSWORD: "secret"
