version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
          - 9000:80
        volumes:
          - ./:/var/www/app
          - ./nginx:/etc/nginx/conf.d

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql

    app:
        build:
            args:
                xdebug: ${APP_DEBUG}
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/app
            - /var/www/app/vendor
